---
timeout: 1800s
steps:
  - name: eu.gcr.io/$PROJECT_ID/cloudbuild-containers:latest
    entrypoint: /bin/bash
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        sudo mkdir -p /workspace/.terraform.d/plugin-cache
        export TF_PLUGIN_CACHE_DIR=/workspace/.terraform.d/plugin-cache
        sudo chown -R developer:developer /workspace
        sudo chown -R developer:developer /builder/home
        git init
        git checkout -b ${BRANCH_NAME}
        git add --all
        gcloud config set auth/impersonate_service_account ${_TF_SA_EMAIL}
  # terragrunt init and validate
  - name: eu.gcr.io/$PROJECT_ID/cloudbuild-containers:latest
    entrypoint: /bin/bash
    env:
      - 'TF_PLUGIN_CACHE_DIR=/workspace/.terraform.d/plugin-cache'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        gcloud config set auth/impersonate_service_account ${_TF_SA_EMAIL}
        cd org
        terragrunt run-all init --terragrunt-non-interactive -input=false -no-color
        terragrunt run-all validate --terragrunt-non-interactive -no-color
        echo "Terragrunt Init finalizat cu succes!"
  # terragrunt plan
  - name: eu.gcr.io/$PROJECT_ID/cloudbuild-containers:latest
    entrypoint: /bin/bash
    env:
      - 'TF_PLUGIN_CACHE_DIR=/workspace/.terraform.d/plugin-cache'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |-
        gcloud config set auth/impersonate_service_account ${_TF_SA_EMAIL}
        cd org
        terragrunt run-all plan --terragrunt-non-interactive -input=false -lock-timeout=60s -no-color
        echo "Terragrunt plan finalizat cu succes!"
options:
  machineType: 'E2_HIGHCPU_8'
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/plan/${BUILD_ID}'
    paths: ['cloudbuild-tg-plan.yaml']
